### ISSUE TITLE
Does not run on non-deb systems

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/appimagelint#11]
The AppImage does not run on non-deb systems such as openSUSE:

```
FileNotFoundError: [Errno 2] No such file or directory: 'dpkg': 'dpkg'
```

If it is needed, then it should be bundled.

**Comment by TheAssassin** [comment]
Replaced the call with a combination of `ar` and `tar` (should be available more widely). Please test and reopen if necessary.
