### ISSUE TITLE
Make it possible to use offline

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/appimagelint#15]
Please make it possible to use this tool offline.
This means bundling (at AppImage creation time) rather than downloading (at runtime) version data.

Use cases:
* Trains with bad/no internet
* OBS

**Comment by TheAssassin** [comment]
CC @adrianschroeter. 

For OBS, a packaging method that comes with the data would be preferable. It also shouldn't attempt to download/update anything at first, as those timeouts are just a waste of time in OBS VMs, as they don't have a connection to the Internet anyway.
