### ISSUE TITLE
Broken on Travis and GitHub Actions from mismatched version info

### ISSUE THREAD

**Issue by lynxlynxlynx** [TheAssassin/appimagelint#22]
The problem is that the chosen mirror prunes its Ubuntu archive, while appimagelint expects it to have more, since Launchpad lists everything. The second exception looks like it could be solved by just rebuilding the caches.

Example:
 ```python
  appimagelint.setup[10630] [INFO] Fetching glibc package versions from Ubuntu FTP mirror
  Warning: int.cache[10630] [WARNING] codebase changed since last update, but updating failed, using cached data
  Error: elint.cache[10630] [ERROR] 404 Client Error: Not Found for url: https://ftp.fau.de/ubuntu/dists/precise/main/binary-amd64/Packages.gz
  Traceback (most recent call last):
    File "/tmp/.mount_appimaFdl42Q/usr/conda/lib/python3.7/site-packages/appimagelint/cache/json_cache_impl_base.py", line 101, in get_data
      new_data = cls._fetch_data()
    File "/tmp/.mount_appimaFdl42Q/usr/conda/lib/python3.7/site-packages/appimagelint/cache/package_version_maps.py", line 17, in _fetch_data
      return get_map_callback()
    File "/tmp/.mount_appimaFdl42Q/usr/conda/lib/python3.7/site-packages/appimagelint/cache/package_version_maps.py", line 29, in <lambda>
      "ubuntu", "glibc", lambda: get_ubuntu_package_versions_map("glibc"), "ubuntu_glibc_versions.json"
    File "/tmp/.mount_appimaFdl42Q/usr/conda/lib/python3.7/site-packages/appimagelint/cache/common.py", line 83, in get_ubuntu_package_versions_map
      data = get_packages_gz_from_ftp_mirror("ubuntu", release)
    File "/tmp/.mount_appimaFdl42Q/usr/conda/lib/python3.7/site-packages/appimagelint/cache/common.py", line 67, in get_packages_gz_from_ftp_mirror
      response.raise_for_status()
    File "/tmp/.mount_appimaFdl42Q/usr/conda/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
      raise HTTPError(http_error_msg, response=self)
  requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ftp.fau.de/ubuntu/dists/precise/main/binary-amd64/Packages.gz

  Traceback (most recent call last):
    File "/tmp/.mount_appimaFdl42Q/usr/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/tmp/.mount_appimaFdl42Q/usr/conda/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/tmp/.mount_appimaFdl42Q/usr/conda/lib/python3.7/site-packages/appimagelint/__main__.py", line 4, in <module>
      run()
    File "/tmp/.mount_appimaFdl42Q/usr/conda/lib/python3.7/site-packages/appimagelint/cli.py", line 142, in run
      for testres in check.run():
    File "/tmp/.mount_appimaFdl42Q/usr/conda/lib/python3.7/site-packages/appimagelint/checks/gnu_abi_check_base.py", line 79, in run
      for result in self._check_ubuntu_compat(required_version):
    File "/tmp/.mount_appimaFdl42Q/usr/conda/lib/python3.7/site-packages/appimagelint/checks/gnu_abi_check_base.py", line 131, in _check_ubuntu_compat
      max_supported_version = versions_map[release]
  KeyError: 'hirsute'
```

**Comment by TheAssassin** [comment]
Two solutions: either update the mirror, or (better) filter EOL dists in https://github.com/TheAssassin/appimagelint/blob/51b4e5543fb4a13d1e6e71b45ca46e8060daa7fe/appimagelint/cache/ubuntu_release_names_cache.py#L12. PRs welcome.

**Comment by lynxlynxlynx** [comment]
They're already filtered enough, currently only returning `['hirsute', 'groovy', 'focal', 'bionic', 'xenial', 'trusty']`. So both problems might go away with a cache rebuild. Are these stored, pre-cached in the generated appimage?

**Comment by TheAssassin** [comment]
The cache is in `~/.cache/appimagelint/ubuntu*`. It should be rebuilt occassionally. I didn't anticipate a condition like this one, really, where launchpad and the mirrors are not on par. We might have to reduce the cache timeout.

**Comment by lynxlynxlynx** [comment]
Ah, it's in `usr/conda/lib/python3.7/site-packages/appimagelint/bundled_cache/` in the image.

**Comment by TheAssassin** [comment]
Don't you have a local cache?

Edit: I think we can also set up a scheduled build every week to update the bundled cache. But the local cache should be up to date.

**Comment by lynxlynxlynx** [comment]
I do, that's fine — this issue is about build bots, where there's no real state.

**Comment by TheAssassin** [comment]
Well, the cache is seeded when outdated or when it does not exist. Look at your log:

```
 Warning: int.cache[10630] [WARNING] codebase changed since last update, but updating failed, using cached data
```

Something prevents the cache from being built. Therefore it uses the bundled cache. You have some permissions issue in your setup.

**Comment by lynxlynxlynx** [comment]
You say that like I'm running Github or Travis. I imagine XDG_CACHE_HOME is not set and it tries to write to /appimagelint:
https://github.com/TheAssassin/appimagelint/blob/51b4e5543fb4a13d1e6e71b45ca46e8060daa7fe/appimagelint/cache/cache_base.py#L13-L15
EDIT: ah, that actually results in CWD/appimagelint. Which is in the readonly mount, I guess, so it fails all the same.

**Comment by TheAssassin** [comment]
I don't know what you're running it on. I've seen the weirdest things in CI systems. For instance, people running with `docker run --user` with a user ID that does not exist in the docker container will see issues with the XDG paths.

The `xdg` library should implement `~/.cache` as a fallback if the var is not set. But if you're running on Travis or in GitHub actions, you're in a regular VM, and the values should be set.

**Comment by lynxlynxlynx** [comment]
It's the bionic image on both projects (xenial for ja2s' Travis), without docker or anything weird. $HOME is not touched. 

Anyway, probably it's not a path issue. Looking at the code, aren't we running in circles? It tries to update, but the mirror has been pruned, so that fails, so the update fails, so the bundled ones are used.
https://github.com/TheAssassin/appimagelint/blob/51b4e5543fb4a13d1e6e71b45ca46e8060daa7fe/appimagelint/cache/json_cache_impl_base.py#L100-L105

**Comment by TheAssassin** [comment]
No, we're not running in circles. Distro names are one kind of data that is cached, and should be updated into local cache first. Distro glibc data is what causes the warning you refer to. At least as far as I can see.

**Comment by lynxlynxlynx** [comment]
So maybe it was a launchpad problem, though it persisting for a few days would be odd. JA2S now runs appimagelint fine again (6 days ago). I'll go try reenabling it on GemRB to see what happens.

**Comment by lynxlynxlynx** [comment]
Yeah, it's still fine now, just closing.

**Comment by TheAssassin** [comment]
Weird. In any case I'll consider rebuilding the tool regularly (e.g., every week).
