### ISSUE TITLE
AppRun error, No such file or directory

### ISSUE THREAD

**Issue by ReenigneArcher** [TheAssassin/appimagelint#25]
Command:
```bash
wget https://github.com/TheAssassin/appimagelint/releases/download/continuous/appimagelint-x86_64.AppImage && chmod +x appimagelint-x86_64.AppImage && ./appimagelint-x86_64.AppImage ./sunshine.AppImage
```

Output:
```txt
/tmp/.mount_appimacImzR4/AppRun: line 9: /tmp/.mount_appimacImzR4/usr/bin/python: No such file or directory
```

I extracted the appimagelint AppImage and do see a `/usr/bin/python` file so not really sure what is going on.

**Comment by probonopd** [comment]
Where can `sunshine.AppImage` be downloaded so that we can reproduce this?

**Comment by ReenigneArcher** [comment]
I get the same warning no matter what AppImage I use or even if I just try to run your AppImage without any arguments. The error is occurring during extraction of the appimagelint AppImage.

Also the same commands are working fine in a github runner, but locally in a VM is when I receive the error.

**Comment by TheAssassin** [comment]
This issue is clearly on your end, and I doubt anyone could ever reproduce it outside your VM. Please consider setting up the VM again.
