### ISSUE TITLE
appimagelint check fails on itself

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/appimagelint#5]
580e368 on `xubuntu-19.04-desktop-amd64.iso`:

```
me@host:~$ ./appimagelint-x86_64.AppImage ./appimagelint-x86_64.AppImage
(...)
appimagelint.icon_check[3858] [INFO] Extracting icon name from desktop file: /tmp/.mount_appimaG0IjOz/appimagelint.desktop
appimagelint.icon_check[3858] [INFO] [✖] Valid icon in AppDir root
appimagelint.icon_check[3858] [ERROR] Failed to identify icon /tmp/.mount_appimaG0IjOz/.DirIcon
Traceback (most recent call last):
  File "/tmp/.mount_appimaLTNErW/usr/conda/lib/python3.7/site-packages/appimagelint/checks/icons.py", line 251, in _get_icon_res
    im = Image.open(icon_path)
  File "/tmp/.mount_appimaLTNErW/usr/conda/lib/python3.7/site-packages/PIL/Image.py", line 2705, in open
    % (filename if filename else fp))
OSError: cannot identify image file '/tmp/.mount_appimaG0IjOz/.DirIcon'
appimagelint.icon_check[3858] [INFO] [✖] Valid icon file in .DirIcon
appimagelint.icon_check[3858] [WARNING] icon /tmp/.mount_appimaG0IjOz/usr/share/icons/hicolor/scalable/apps/appimagelint.svg has invalid resolution
appimagelint.icon_check[3858] [ERROR] Icon resolution doesn't match resolution in path: scalable (file resolution is None)
appimagelint.icon_check[3858] [INFO] [✖] Other integration icons valid

me@host:~$ ./appimagelint-x86_64.AppImage --version
usage: appimagelint [-h] [--debug] [--log-source-location] [--log-timestamps]
                    [--force-colors] [--json-report [JSON_REPORT]]
                    path [path ...]
appimagelint: error: the following arguments are required: path
```

**Comment by TheAssassin** [comment]
Right, that's because there's no icon for it. I can just put in the normal AppImage logo, if that's fine for you.

There's no `--version` parameter since there's no versioning yet.

**Comment by probonopd** [comment]
Should it not just say  `[INFO] [✖] Valid icon file in .DirIcon` rather than

```
Traceback (most recent call last):
  File "/tmp/.mount_appimaLTNErW/usr/conda/lib/python3.7/site-packages/appimagelint/checks/icons.py", line 251, in _get_icon_res
    im = Image.open(icon_path)
  File "/tmp/.mount_appimaLTNErW/usr/conda/lib/python3.7/site-packages/PIL/Image.py", line 2705, in open
    % (filename if filename else fp))
OSError: cannot identify image file '/tmp/.mount_appimaG0IjOz/.DirIcon'
```
?

The "version" I was looking for is 580e368... ;-)

**Comment by TheAssassin** [comment]
Not IMO. This is what we get from Pillow (Python Imaging Library (PIL) successor). It clearly tells that there's an *invalid* file there, i.e., the file exists, but it can't be identified. What could be added is a check in advance whether we have an empty file there. But unfortunately there's no real way to differentiate between `OSError`s like "could not open file" (for whatever reason) etc., and what PIL returns. They should IMO return a properly named exception which could be handled with a nice error message. But that doesn't exist.

**Comment by probonopd** [comment]
`Traceback (most recent call last):` to me reads "the tool is broken" rather than "the tool has detected an error in the AppImage under test". Why not put the whole thing into a `try: except:` statement?

**Comment by TheAssassin** [comment]
>  But unfortunately there's no real way to differentiate between OSErrors like "could not open file" (for whatever reason) etc., and what PIL returns. They should IMO return a properly named exception which could be handled with a nice error message. But that doesn't exist.

**Comment by probonopd** [comment]
It is not important _why_ it fails, only _that_ it fails. If it fails, assume there is no correct icon.

**Comment by TheAssassin** [comment]
A linter shall always give feedback on the "why" too. There's no point in automatically checking stuff without providing feedback how to do better. There's a ton of reasons an icon can be "incorrect" or "broken". We have that information anyway since we try to parse the icon anyway, therefore it's pretty simple to forward that information to the user.
The fact that there's a traceback might be a bit "terrifying" to people, but to me, a printed traceback is just something perfectly normal in an error situation.
